### PR TITLE
Try to fix known things and add some features requested

### PR DESCRIPTION
**Pull request by ItsToxicGG**
This is a test and will be tested, ill make sure it does not have lints and its ok:D

### CODE REVIEW

**Comment by ItsToxicGG** [comment]
fix all the 2 lints

**Comment by ItsToxicGG** [comment]
ill test it now

**Comment by ItsToxicGG** [comment]
ill give you infomation if it worked or not then ill work on the next one (not spawn at the world spawn)

**Comment by ItsToxicGG** [comment]
# Fixes Todo:
- [X] Fix When Game Ends, a players inventory dont clear (Done)
- [ ] Fix when dying spawn on the worlds spawn (NOT YET)
# Features Todo:
- [ ]  Implement Custom Kit (this was a feature asked to do)

**Comment by SandhyR** [comment]
Don't import external virions directly into the plugin, use .poggit.yml

**Comment by SandhyR** [comment]
Don't import external virions directly into the plugin, use .poggit.yml

**Comment by ItsToxicGG** [comment]
> virions directly into the plugin, use .poggit.yml

ALRIGHT

**Comment by ItsToxicGG** [comment]
3 PHPStan Lints ima tryna fix

**Comment by ItsToxicGG** [comment]
This is turning to a mess ima close...

**Pull request closed without merging**
